source = ./animations.conf

bind = WIN, F1, exec, ~/.config/hypr/scripts/fancy.sh
bind = WIN, F2, exec, ~/.config/hypr/scripts/animations.sh

general {
    gaps_in = 4
    gaps_out = 8

    border_size = 1

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgb(e2e2e2)
    col.inactive_border = rgb(6E6E6E)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    # Keep on to allow tearing the screen for gaming
    # make sure to add immediate windowrules for the games
    allow_tearing = true

    layout = dwindle
}

group {
    col.border_active = rgb(e2e2e2)
    col.border_inactive = rgb(6E6E6E)

    groupbar {
        enabled = true
        gradients = true
        gaps_in = 0
        gaps_out = 0
        keep_upper_gap = false
        col.active = rgb(333332)
        col.inactive = rgb(6E6E6E)
        stacked = false
    }
}

# smart gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
# windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
# windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

# blur layers (panel)
# layerrule = blur, quickshell

##############################

decoration {
    rounding = 15

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    # blur {
    #     enabled = true
    #     size = 10
    #     passes = 3
    #
    #     vibrancy = 0.1
    # }
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        ignore_opacity = false
        #vibrancy = 0.1
    }
}



misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}
